---
- hosts: all
  become: true
  tasks:

  - name: install apache and php packages for Linux Mint
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Linux Mint"

  - name: install apache and php packages for Rocky Linux
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Rocky"
